### ISSUE TITLE
Crystal 0.31.1 Error: undefined method 'epoch' for Time.class

### ISSUE THREAD

**Issue by bendangelo** [discordcr/discordcr#196]
Using crystal 0.31.1.

```
In lib/discordcr/src/discordcr/rest.cr:56:31

 56 | reset_time = Time.epoch(response.headers["X-RateLimit-Reset"].to_u64) # gotta prevent that Y2k38
                        ^----
Error: undefined method 'epoch' for Time.class
````

**Comment by Daniel-Worrall** [comment]
This was fixed in #167
Then again, for latest support you'll need to use a fork.

https://github.com/z64/discordcr/tree/crystal-0.28
Unsure if it's working with 0.31.1, but it was working with 0.30.1 iirc

**Comment by r00ster91** [comment]
You don't need a fork. Just add `branch: master` to your `shard.yml`:
```yml
dependencies:
  discordcr:
    github: meew0/discordcr
    branch: master
```

**Comment by bendangelo** [comment]
ok thanks

**Comment by bendangelo** [comment]
This project is still used but it seems the maintainer is inactive. Can he give someone permission to maintain this? @meew0

**Comment by z64** [comment]
The related PR for this issue has been merged, along with other fixes Crystal changes,  and will be available in the next release / `master` if you want to use it right now. Thank you for taking the time to report.

**Comment by RX14** [comment]
@z64 congrats on finally managing to merge these PRs :)
